import { useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, BriefcaseBusiness, Check, ChevronRight, CircleUserRound, Download, ExternalLink, FileJson, FileText, Files, Globe2, LayoutDashboard, LoaderCircle, Play, Plus, RefreshCw, Save, ShieldCheck, Sparkles, Trash2, UploadCloud, WandSparkles, X } from 'lucide-react'
import { API, ApiError, api } from './api'
import type { BrowserSnapshot, CandidateProfile, Conflict, Education, Evidence, ExecutionResult, Experience, FillAction, FormPlan, PreSubmitCheck, Project, ResumeProfile, ResumeRecord } from './types'

type Page='overview'|'profile'|'resumes'|'review'|'demo'
const emptyEducation:Education={school:'',college:'',degree:'',major:'',start_date:'',end_date:'',gpa:'',ranking:'',courses:[],description:'',current:false}
const emptyExperience:Experience={organization:'',department:'',role:'',employment_type:'',location:'',start_date:'',end_date:'',current:false,description:'',achievements:[],technologies:[]}
const emptyProject:Project={name:'',role:'',start_date:'',end_date:'',background:'',description:'',achievements:[],technologies:[],project_url:'',github_url:''}
const labels:Record<string,string>={name:'姓名',english_name:'英文姓名',gender:'性别',birth_date:'出生日期',age:'年龄',phone:'手机号',email:'邮箱',wechat:'微信',location:'当前城市',hometown:'籍贯',website:'个人网站',github:'GitHub',linkedin:'LinkedIn',target_role:'目标岗位',available_date:'可入职时间',internship_duration:'实习时长',days_per_week:'每周天数',expected_salary:'期望薪资',remote_preference:'远程偏好',summary:'个人简介',education:'教育经历',internships:'实习经历',projects:'项目经历',skills:'技能'}

export default function App(){
  const [page,setPage]=useState<Page>('overview'); const [profile,setProfile]=useState<CandidateProfile|null>(null)
  const [resumes,setResumes]=useState<ResumeRecord[]>([]); const [conflicts,setConflicts]=useState<Conflict[]>([])
  const [selected,setSelected]=useState(''); const [rawText,setRawText]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('')
  const fileInput=useRef<HTMLInputElement>(null)
  const reload=async()=>{try{const [p,r,c]=await Promise.all([api.profile(),api.list(),api.conflicts()]);setProfile(p);setResumes(r);setConflicts(c);if(!selected&&r[0])setSelected(r[0].id)}catch(e){setNotice(message(e))}}
  useEffect(()=>{reload()},[])
  useEffect(()=>{if(page!=='review'||!selected)return;let active=true;setRawText('');api.text(selected).then(data=>{if(active)setRawText(data.text)}).catch(e=>{if(active)setNotice(message(e))});return()=>{active=false}},[page,selected])
  const active=resumes.find(r=>r.id===selected)??null
  const upload=async(file?:File)=>{if(!file)return;setBusy(true);setNotice('Agent 正在读取、拆分并合并资料…');try{const item=await api.upload(file);await reload();setSelected(item.id);setPage('review');setNotice('解析完成。请检查识别证据和冲突。')}catch(e){if(e instanceof ApiError&&typeof e.detail==='object'&&e.detail&&'resume_id' in e.detail){await reload();setSelected(String((e.detail as {resume_id:unknown}).resume_id));setPage('resumes')}setNotice(message(e))}finally{setBusy(false);if(fileInput.current)fileInput.current.value=''}}
  const openReview=(id:string)=>{setSelected(id);setPage('review')}
  const updateResumeLocal=(item:ResumeRecord)=>setResumes(all=>all.map(r=>r.id===item.id?item:r))
  const nav=[['overview','总览',LayoutDashboard],['profile','主档案',CircleUserRound],['resumes','简历资料库',Files],['review','待确认',AlertTriangle],['demo','网站 Demo',Globe2]] as const
  return <div className="shell"><aside><div className="brand"><span><BriefcaseBusiness size={20}/></span><div><strong>职达 Zhida</strong><small>求职资料 Agent</small></div></div>
    <button className="primary full" onClick={()=>fileInput.current?.click()} disabled={busy}><Plus size={17}/>上传新简历</button><input ref={fileInput} hidden type="file" accept=".pdf,.docx,.txt" onChange={e=>upload(e.target.files?.[0])}/>
    <nav>{nav.map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}><Icon size={18}/>{label}{key==='review'&&<b>{conflicts.length+resumes.flatMap(r=>r.evidence).filter(e=>e.status==='pending_review').length}</b>}</button>)}</nav>
    <div className="privacy"><ShieldCheck size={17}/><div><strong>受控模型传输</strong><small>只在解析与匹配时发送</small></div></div></aside>
    <main><Top page={page}/>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
      {page==='overview'&&profile&&<Overview profile={profile} resumes={resumes} conflicts={conflicts} go={setPage}/>}
      {page==='profile'&&profile&&<ProfileEditor profile={profile} onSave={async p=>{setBusy(true);try{setProfile(await api.saveProfile(p));setNotice('主档案已保存。')}catch(e){setNotice(message(e))}finally{setBusy(false)}}}/>}
      {page==='resumes'&&<ResumeLibrary resumes={resumes} busy={busy} upload={()=>fileInput.current?.click()} onReview={openReview} onRefresh={async r=>{setBusy(true);try{updateResumeLocal(await api.reparse(r.id));await reload();setNotice('重新解析完成。')}catch(e){await reload();setNotice(message(e))}finally{setBusy(false)}}} onDefault={async r=>{updateResumeLocal(await api.saveResume(r.id,{is_default:true}));await reload()}} onDelete={async r=>{if(!confirm(`确定删除“${r.label}”及其原始文件吗？`))return;await api.deleteResume(r.id);await reload();setNotice('简历及原始文件已删除。')}}/>}
      {page==='review'&&<ReviewWorkspace resumes={resumes} active={active} conflicts={conflicts} rawText={rawText} select={openReview} notify={setNotice} onReviewed={async item=>{updateResumeLocal(item);setProfile(await api.profile())}} onResolved={async(id,choice,custom)=>{await api.resolve(id,choice,custom);await reload();setNotice('冲突已处理，主档案已更新。')}}/>}
      {page==='demo'&&<BrowserDemo profile={profile} resumes={resumes} notify={setNotice}/>}
    </main></div>
}

function Top({page}:{page:Page}){const copy={overview:['候选人资料总览','一次维护，反复用于之后的每次申请。'],profile:['候选人主档案','这里是你的事实来源，Agent 不会擅自覆盖已确认信息。'],resumes:['简历资料库','管理不同语言、岗位方向和版本的简历。'],review:['识别结果检查','对照原文确认 Agent 拆分的字段，并处理资料冲突。'],demo:['招聘网站填写 Demo','让 Agent 理解表单，由 Playwright 安全执行，永不自动提交。']}[page];return <header><div><p className="eyebrow">ZHIDA / PROFILE WORKSPACE</p><h1>{copy[0]}</h1><p>{copy[1]}</p></div><a className="export" href={`${API}/export`} target="_blank"><FileJson size={17}/>导出 JSON</a></header>}

function Overview({profile,resumes,conflicts,go}:{profile:CandidateProfile;resumes:ResumeRecord[];conflicts:Conflict[];go:(p:Page)=>void}){
  const pending=resumes.flatMap(r=>r.evidence).filter(e=>e.status==='pending_review').length
  const fields=[profile.name,profile.phone,profile.email,profile.location,profile.target_role,profile.summary,profile.education.length,profile.internships.length,profile.projects.length,profile.skills.length]
  const complete=Math.round(fields.filter(Boolean).length/fields.length*100)
  return <><section className="metric-grid"><Metric label="资料完整度" value={`${complete}%`} note="继续补充可提升投递覆盖" tone="green"/><Metric label="简历版本" value={String(resumes.length)} note={resumes.some(r=>r.is_default)?'已设置默认版本':'还没有默认简历'}/><Metric label="待确认字段" value={String(pending)} note="确认后成为可信资料"/><Metric label="信息冲突" value={String(conflicts.length)} note={conflicts.length?'需要你做最终选择':'目前没有冲突'} tone={conflicts.length?'amber':'green'}/></section>
    <section className="overview-grid"><div className="card profile-hero"><div className="avatar">{profile.name?.[0]||'职'}</div><div><p>候选人主档案</p><h2>{profile.name||'尚未填写姓名'}</h2><span>{profile.target_role||'添加目标岗位'} · {profile.location||'添加当前城市'}</span></div><button onClick={()=>go('profile')}>编辑档案<ChevronRight size={16}/></button></div>
    <div className="card next-step"><Sparkles size={22}/><div><h3>下一步建议</h3><p>{pending?`还有 ${pending} 个识别字段等待确认。`:'上传一份新的简历，Agent 会自动合并新增经历。'}</p></div><button onClick={()=>go(pending?'review':'resumes')}>开始处理</button></div></section>
    <section className="card"><SectionTitle n="资料" title="经历素材概览" sub="主档案中的可复用事实"/><div className="fact-row"><Fact n={profile.education.length} label="教育经历"/><Fact n={profile.internships.length} label="实习经历"/><Fact n={profile.projects.length} label="项目经历"/><Fact n={profile.skills.length} label="技能关键词"/></div></section></>}
function Metric({label,value,note,tone=''}:{label:string;value:string;note:string;tone?:string}){return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Fact({n,label}:{n:number;label:string}){return <div><strong>{n}</strong><span>{label}</span></div>}

function ProfileEditor({profile,onSave}:{profile:CandidateProfile;onSave:(p:ResumeProfile)=>void}){
  const [draft,setDraft]=useState<ResumeProfile>(profile);useEffect(()=>setDraft(profile),[profile])
  const set=(key:keyof ResumeProfile,value:unknown)=>setDraft(d=>({...d,[key]:value}))
  return <div className="stack"><section className="card"><SectionTitle n="01" title="基本信息" sub="敏感信息只由你填写或确认"/><div className="form-grid three">
    <Input label="姓名" value={draft.name} set={v=>set('name',v)}/><Input label="英文姓名" value={draft.english_name} set={v=>set('english_name',v)}/><Select label="性别" value={draft.gender} values={['未识别','男','女','其他']} set={v=>set('gender',v)}/><Input label="出生日期" type="date" value={draft.birth_date} set={v=>set('birth_date',v)}/><Input label="年龄" type="number" value={draft.age} set={v=>set('age',v?Number(v):null)}/><Input label="手机号" value={draft.phone} set={v=>set('phone',v)}/><Input label="邮箱" type="email" value={draft.email} set={v=>set('email',v)}/><Input label="微信" value={draft.wechat} set={v=>set('wechat',v)}/><Input label="当前城市" value={draft.location} set={v=>set('location',v)}/><Input label="籍贯" value={draft.hometown} set={v=>set('hometown',v)}/><Input label="GitHub" value={draft.github} set={v=>set('github',v)}/><Input label="LinkedIn" value={draft.linkedin} set={v=>set('linkedin',v)}/><Input label="个人网站" value={draft.website} set={v=>set('website',v)}/></div><Text label="个人简介" value={draft.summary} set={v=>set('summary',v)}/></section>
    <section className="card"><SectionTitle n="02" title="求职偏好" sub="后续用于职位筛选和申请表单"/><div className="form-grid three"><Input label="目标岗位" value={draft.target_role} set={v=>set('target_role',v)}/><Input label="目标城市（逗号分隔）" value={draft.target_cities.join('，')} set={v=>set('target_cities',split(v))}/><Input label="目标行业（逗号分隔）" value={draft.target_industries.join('，')} set={v=>set('target_industries',split(v))}/><Input label="可入职时间" value={draft.available_date} set={v=>set('available_date',v)}/><Input label="实习时长" value={draft.internship_duration} set={v=>set('internship_duration',v)}/><Input label="每周可实习天数" value={draft.days_per_week} set={v=>set('days_per_week',v)}/><Input label="期望薪资" value={draft.expected_salary} set={v=>set('expected_salary',v)}/><Input label="远程偏好" value={draft.remote_preference} set={v=>set('remote_preference',v)}/></div></section>
    <EditableList title="教育经历" n="03" items={draft.education} empty={emptyEducation} set={v=>set('education',v)} render={(x,i,edit)=><div className="form-grid three"><Input label="学校" value={x.school} set={v=>edit(i,{school:v})}/><Input label="学院" value={x.college} set={v=>edit(i,{college:v})}/><Input label="专业" value={x.major} set={v=>edit(i,{major:v})}/><Input label="学历" value={x.degree} set={v=>edit(i,{degree:v})}/><Input label="开始时间" value={x.start_date} set={v=>edit(i,{start_date:v})}/><Input label="毕业时间" value={x.end_date} set={v=>edit(i,{end_date:v})}/><Input label="GPA" value={x.gpa} set={v=>edit(i,{gpa:v})}/><Input label="排名" value={x.ranking} set={v=>edit(i,{ranking:v})}/></div>}/>
    <EditableList title="实习经历" n="04" items={draft.internships} empty={emptyExperience} set={v=>set('internships',v)} render={(x,i,edit)=><><div className="form-grid three"><Input label="公司/组织" value={x.organization} set={v=>edit(i,{organization:v})}/><Input label="部门" value={x.department} set={v=>edit(i,{department:v})}/><Input label="职位" value={x.role} set={v=>edit(i,{role:v})}/><Input label="地点" value={x.location} set={v=>edit(i,{location:v})}/><Input label="开始时间" value={x.start_date} set={v=>edit(i,{start_date:v})}/><Input label="结束时间" value={x.end_date} set={v=>edit(i,{end_date:v})}/></div><Text label="工作内容" value={x.description} set={v=>edit(i,{description:v})}/></>}/>
    <EditableList title="项目经历" n="05" items={draft.projects} empty={emptyProject} set={v=>set('projects',v)} render={(x,i,edit)=><><div className="form-grid three"><Input label="项目名称" value={x.name} set={v=>edit(i,{name:v})}/><Input label="角色" value={x.role} set={v=>edit(i,{role:v})}/><Input label="开始时间" value={x.start_date} set={v=>edit(i,{start_date:v})}/><Input label="结束时间" value={x.end_date} set={v=>edit(i,{end_date:v})}/><Input label="技术栈（逗号分隔）" value={x.technologies.join('，')} set={v=>edit(i,{technologies:split(v)})}/><Input label="GitHub" value={x.github_url} set={v=>edit(i,{github_url:v})}/></div><Text label="项目描述" value={x.description} set={v=>edit(i,{description:v})}/></>}/>
    <section className="card"><SectionTitle n="06" title="技能与补充资料" sub="使用逗号分隔多个项目"/><div className="form-grid two"><Text label="技能" value={draft.skills.join('，')} set={v=>set('skills',split(v))}/><Text label="语言能力" value={draft.languages.join('，')} set={v=>set('languages',split(v))}/><Text label="证书" value={draft.certificates.join('，')} set={v=>set('certificates',split(v))}/><Text label="奖项" value={draft.awards.join('，')} set={v=>set('awards',split(v))}/></div></section>
    <div className="sticky-save"><span>主档案是 Agent 后续工作的事实基础</span><button className="primary" onClick={()=>onSave(draft)}><Save size={17}/>保存主档案</button></div></div>}

function ResumeLibrary({resumes,busy,upload,onReview,onRefresh,onDefault,onDelete}:{resumes:ResumeRecord[];busy:boolean;upload:()=>void;onReview:(id:string)=>void;onRefresh:(r:ResumeRecord)=>void;onDefault:(r:ResumeRecord)=>void;onDelete:(r:ResumeRecord)=>void}){return <section className="card"><div className="library-head"><SectionTitle n={String(resumes.length).padStart(2,'0')} title="简历版本" sub="支持 PDF、DOCX、TXT，单份最大 10MB"/><button className="primary" onClick={upload}><UploadCloud size={17}/>上传简历</button></div>{!resumes.length?<div className="empty"><UploadCloud size={30}/><h2>还没有简历</h2><p>上传后，Agent 会自动拆分并合并到主档案。</p></div>:<div className="resume-grid">{resumes.map(r=><article className="resume-card" key={r.id}><div className="file-icon"><Files size={22}/></div><div className="resume-main"><div><h3>{r.label}{r.is_default&&<em>默认</em>}</h3><p>{r.filename}</p></div><div className="tag-row"><span>{r.language}</span><span>{formatBytes(r.file_size)}</span><span>{r.status==='failed'?'解析失败':r.status==='parsing'?'解析中':r.parser==='local-rules'?'本地解析':'AI 解析'}</span></div><small>{r.status==='failed'?(r.error_message||'模型服务暂时不可用，请重新解析'):`${r.evidence.filter(e=>e.status==='pending_review').length} 个字段待确认 · ${new Date(r.updated_at).toLocaleDateString('zh-CN')}`}</small></div><div className="actions"><button disabled={r.status==='failed'||r.status==='parsing'} onClick={()=>onReview(r.id)}>检查</button><a href={`${API}/resumes/${r.id}/download`}><Download size={15}/></a><button title="重新解析" disabled={busy||r.status==='parsing'} onClick={()=>onRefresh(r)}><RefreshCw size={15}/></button>{!r.is_default&&<button title="设为默认" disabled={r.status==='failed'||r.status==='parsing'} onClick={()=>onDefault(r)}><Check size={15}/></button>}<button className="danger" title="删除" onClick={()=>onDelete(r)}><Trash2 size={15}/></button></div></article>)}</div>}</section>}

function ReviewWorkspace({resumes,active,conflicts,rawText,select,notify,onReviewed,onResolved}:{resumes:ResumeRecord[];active:ResumeRecord|null;conflicts:Conflict[];rawText:string;select:(id:string)=>void;notify:(v:string)=>void;onReviewed:(r:ResumeRecord)=>Promise<void>;onResolved:(id:string,c:'current'|'incoming'|'custom',v?:unknown)=>void}){
  const [tab,setTab]=useState<'fields'|'conflicts'>('fields')
  const [sourceView,setSourceView]=useState<'file'|'text'>('file')
  useEffect(()=>setSourceView('file'),[active?.id])
  const pendingEvidence=active?.evidence.filter(e=>e.status==='pending_review')??[]
  return <div className="stack"><div className="review-toolbar"><select value={active?.id||''} onChange={e=>select(e.target.value)}><option value="">选择简历</option>{resumes.map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select><div><button className={tab==='fields'?'active':''} onClick={()=>setTab('fields')}>识别字段</button><button className={tab==='conflicts'?'active':''} onClick={()=>setTab('conflicts')}>资料冲突 <b>{conflicts.length}</b></button></div></div>
    {tab==='conflicts'?<ConflictList conflicts={conflicts} resolve={onResolved}/>:!active?<div className="card empty"><Files size={28}/><h2>选择一份简历开始检查</h2></div>:<div className="review-grid"><section className="card source"><div className="source-head"><div><h2>{sourceView==='file'?'原始文件预览':'提取文本'}</h2><p>{active.filename}</p></div><div className="source-head-tools"><div className="source-switch"><button className={sourceView==='file'?'active':''} onClick={()=>setSourceView('file')}><Files size={13}/>原始文件</button><button className={sourceView==='text'?'active':''} onClick={()=>setSourceView('text')}><FileText size={13}/>提取文本</button></div><a href={`${API}/resumes/${active.id}/download`} title="下载原始文件"><Download size={15}/></a></div></div>{sourceView==='file'?<iframe className="source-frame" title={`${active.filename} 原始文件预览`} src={`${API}/resumes/${active.id}/preview`}/>:<pre>{rawText||'正在读取提取文本…'}</pre>}</section><section className="card evidence"><div className="source-head"><div><h2>Agent 识别结果</h2><p>处理后会自动从待确认列表收起</p></div><span>{pendingEvidence.length} 待处理</span></div>{pendingEvidence.length?pendingEvidence.map(e=><EvidenceItem key={e.id} item={e} notify={notify} act={async(status,value)=>onReviewed(await api.review(active.id,e.id,status,value))}/>):<div className="success-empty"><ShieldCheck size={30}/><h3>这份简历已检查完成</h3><p>所有字段均已确认、修改或拒绝。</p></div>}</section></div>}</div>}
function EvidenceItem({item,act,notify}:{item:Evidence;act:(s:string,v?:unknown)=>Promise<void>;notify:(v:string)=>void}){const [editing,setEditing]=useState(false);const [value,setValue]=useState(typeof item.value==='string'?item.value:JSON.stringify(item.value,undefined,2));const tone=item.confidence>=.9?'high':item.confidence>=.75?'medium':'low';const submit=async(status:string,next?:unknown)=>{try{await act(status,next);if(status==='edited')notify(`${labels[item.field_path]??item.field_path}已同步到简历版本和主档案。`);return true}catch(e){notify(message(e));return false}};const save=async()=>{let parsed:unknown=value;if(typeof item.value!=='string'){try{parsed=JSON.parse(value)}catch{notify('列表或经历字段必须是有效的 JSON，请检查括号和引号。');return}}if(await submit('edited',parsed))setEditing(false)};return <article className={`evidence-item ${item.status}`}><div className="evidence-top"><strong>{labels[item.field_path]??item.field_path}</strong><span className={tone}>{Math.round(item.confidence*100)}% 置信度</span></div>{editing?<textarea value={value} onChange={e=>setValue(e.target.value)}/>:<div className="evidence-value">{value}</div>}<blockquote>{item.source_text||'未找到直接原文'}</blockquote><div className="evidence-actions"><span>等待确认</span>{editing?<><button onClick={save}>保存修改</button><button onClick={()=>setEditing(false)}>取消</button></>:<><button onClick={()=>submit('confirmed')}><Check size={14}/>确认</button><button onClick={()=>setEditing(true)}>修改</button><button className="reject" onClick={()=>submit('rejected')}>拒绝</button></>}</div></article>}
function ConflictList({conflicts,resolve}:{conflicts:Conflict[];resolve:(id:string,c:'current'|'incoming'|'custom',v?:unknown)=>void}){return <section className="card"><SectionTitle n={String(conflicts.length).padStart(2,'0')} title="资料冲突" sub="新简历不会静默覆盖主档案，请选择真实信息"/>{!conflicts.length?<div className="success-empty"><ShieldCheck size={30}/><h3>没有待处理冲突</h3><p>主档案中的信息目前一致。</p></div>:<div className="conflict-list">{conflicts.map(c=><article key={c.id}><div><span>{labels[c.field_path]??c.field_path}</span><small>来自：{c.resume_label}</small></div><button onClick={()=>resolve(c.id,'current')}><small>保留主档案</small><strong>{display(c.current_value)}</strong></button><button onClick={()=>resolve(c.id,'incoming')}><small>采用新简历</small><strong>{display(c.incoming_value)}</strong></button></article>)}</div>}</section>}

function BrowserDemo({profile,resumes,notify}:{profile:CandidateProfile|null;resumes:ResumeRecord[];notify:(v:string)=>void}){
  const [url,setUrl]=useState('');const [snapshot,setSnapshot]=useState<BrowserSnapshot|null>(null);const [plan,setPlan]=useState<FormPlan|null>(null);const [execution,setExecution]=useState<ExecutionResult|null>(null);const [check,setCheck]=useState<PreSubmitCheck|null>(null);const [answers,setAnswers]=useState<Record<string,string>>({});const [selectedResume,setSelectedResume]=useState('');const [busy,setBusy]=useState('')
  const start=async()=>{setBusy('opening');setPlan(null);setExecution(null);setCheck(null);setAnswers({});try{const data=await api.startBrowser(url);setSnapshot(data);notify(`已打开 ${data.title||data.url}，识别到 ${data.fields.length} 个表单字段。`)}catch(e){notify(message(e))}finally{setBusy('')}}
  const analyze=async()=>{if(!snapshot)return;setBusy('planning');setPlan(null);setExecution(null);setCheck(null);setAnswers({});try{const fresh=await api.browserSnapshot(snapshot.session_id);setSnapshot(fresh);const result=await api.planForm(snapshot.session_id);setPlan(result);notify(`Agent 已生成 ${result.actions.length} 条填写建议。`)}catch(e){notify(message(e))}finally{setBusy('')}}
  const answer=(action:FillAction,value:string)=>{const field=snapshot?.fields.find(f=>f.selector===action.selector);setAnswers(current=>{const next={...current};if(field?.field_type==='radio'&&value==='true')snapshot?.fields.filter(f=>f.name===field.name).forEach(f=>delete next[f.selector]);if(value)next[action.selector]=value;else delete next[action.selector];return next})}
  const preparedActions=useMemo(()=>plan?.actions.map(action=>{const manual=answers[action.selector];if(!manual)return action;const field=snapshot?.fields.find(f=>f.selector===action.selector);const kind=field?.field_type;return {...action,action:(kind==='select-one'||kind==='select-multiple'?'select':kind==='checkbox'||kind==='radio'?'check':'fill') as FillAction['action'],value:kind==='checkbox'||kind==='radio'?manual==='true':manual,confidence:1,sensitive:false,user_confirmed:true,value_source:'用户在提交前补充'}})??[],[plan,answers,snapshot])
  const readyCount=preparedActions.filter(a=>['fill','select','check'].includes(a.action)&&(a.action==='check'||String(a.value).trim())&&(!a.sensitive||a.user_confirmed)&&a.confidence>=.85).length
  const needsInput=plan?.actions.filter(action=>{const field=snapshot?.fields.find(f=>f.selector===action.selector);if(field?.field_type==='file')return false;const emptyAction=!['fill','select','check'].includes(action.action)||(action.action!=='check'&&!String(action.value).trim());return action.action==='ask_user'||action.sensitive||Boolean(field?.required&&emptyAction)})??[]
  const execute=async()=>{if(!snapshot||!plan)return;setBusy('filling');try{const result=await api.executeForm(snapshot.session_id,preparedActions,selectedResume);setExecution(result);setCheck(result.pre_submit);setSnapshot(await api.browserSnapshot(snapshot.session_id));notify(`填写完成：${result.verified} 项已回读验证，${result.failed} 项失败，仍有 ${result.pre_submit.required_missing.length} 个必填项缺失。`)}catch(e){notify(message(e))}finally{setBusy('')}}
  const recheck=async()=>{if(!snapshot)return;setBusy('checking');try{setCheck(await api.checkForm(snapshot.session_id));notify('已重新检查当前网页。')}catch(e){notify(message(e))}finally{setBusy('')}}
  const close=async()=>{if(snapshot)await api.closeBrowser(snapshot.session_id).catch(()=>{});setSnapshot(null);setPlan(null);setExecution(null);setCheck(null);setAnswers({});notify('浏览器 Demo 会话已结束。')}
  return <div className="stack demo-workspace"><section className="card demo-intro"><div><span className="demo-icon"><WandSparkles size={22}/></span><div><h2>自适应表单实验台</h2><p>识别、补充、上传、填写和回读验证，最终停在提交前。</p></div></div><div className="safety-note"><ShieldCheck size={16}/><span>不会点击提交按钮<br/><small>敏感问题只使用你亲自确认的答案</small></span></div></section>
    <section className="card"><SectionTitle n="01" title="打开招聘页面" sub="建议先选择 Greenhouse、Lever 或结构清晰的公开申请页"/><div className="url-row"><label className="field"><span>招聘申请页面 URL</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://boards.greenhouse.io/..." onKeyDown={e=>e.key==='Enter'&&start()}/></label>{snapshot?<button className="secondary" onClick={close}><X size={16}/>结束会话</button>:<button className="primary" disabled={!url||!!busy} onClick={start}>{busy==='opening'?<LoaderCircle className="spin" size={17}/>:<ExternalLink size={17}/>}打开浏览器</button>}</div>{snapshot&&<div className="browser-status"><span className="live-dot"/><div><strong>{snapshot.title||'招聘页面'}</strong><small>{snapshot.url}</small></div><em>{snapshot.fields.length} 个字段</em></div>}</section>
    <section className={`card ${!snapshot?'disabled-card':''}`}><div className="library-head"><SectionTitle n="02" title="让 Agent 分析表单" sub={`使用 ${profile?.name||'当前候选人'} 的已确认主档案生成计划`}/><button className="primary" disabled={!snapshot||!!busy} onClick={analyze}>{busy==='planning'?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>}分析当前页面</button></div>{snapshot&&!plan&&<div className="field-preview">{snapshot.fields.slice(0,8).map(field=><span key={field.selector}>{field.label||field.name||field.field_type}{field.required&&<b>*</b>}</span>)}{snapshot.fields.length>8&&<span>+{snapshot.fields.length-8}</span>}</div>}
      {plan&&<><div className="plan-summary"><div><strong>{plan.site_type}</strong><span>{plan.page_summary}</span></div><div><b>{readyCount}</b><small>已准备填写</small></div><div><b>{needsInput.filter(a=>!answers[a.selector]).length}</b><small>等待用户回答</small></div></div><div className="action-list">{plan.actions.map((action,i)=><article key={`${action.selector}-${i}`} className={answers[action.selector]?'ready':action.action==='ask_user'||action.sensitive?'needs-user':action.action==='skip'?'will-skip':'ready'}><span>{answers[action.selector]?'已补充':action.action==='fill'?'填写':action.action==='select'?'选择':action.action==='check'?'勾选':action.action==='ask_user'?'询问':'跳过'}</span><div><strong>{action.label}</strong><p>{answers[action.selector]||display(action.value)||action.reason}</p><small>{answers[action.selector]?'由用户明确确认':action.value_source||action.reason}</small></div><em>{answers[action.selector]?'100':Math.round(action.confidence*100)}%</em></article>)}</div></>}
    </section>
    {plan&&<section className="card"><SectionTitle n="03" title="补充答案与简历" sub="缺失项可以暂时留空，敏感答案只在你亲自填写后执行"/><div className="form-grid two"><label className="field"><span>本次上传的简历</span><select value={selectedResume} onChange={e=>setSelectedResume(e.target.value)}><option value="">不自动上传</option>{resumes.map(r=><option value={r.id} key={r.id}>{r.label}{r.is_default?' · 默认':''}</option>)}</select></label></div>{needsInput.length?<div className="answer-list">{needsInput.map(action=>{const field=snapshot?.fields.find(f=>f.selector===action.selector);const isToggle=field?.field_type==='radio'||field?.field_type==='checkbox';return <label className="answer-row" key={action.selector}><span><strong>{action.label}</strong><small>{action.reason||'主档案中没有可靠答案'}</small></span>{isToggle?<input type="checkbox" checked={answers[action.selector]==='true'} onChange={e=>answer(action,e.target.checked?'true':'')}/>:field?.options.length?<select value={answers[action.selector]||''} onChange={e=>answer(action,e.target.value)}><option value="">暂不填写</option>{field.options.map(option=><option value={option} key={option}>{option}</option>)}</select>:<input value={answers[action.selector]||''} onChange={e=>answer(action,e.target.value)} placeholder="输入后会标记为用户确认"/>}</label>})}</div>:<div className="success-empty compact"><ShieldCheck size={25}/><h3>没有需要补充的问题</h3></div>}</section>}
    <section className={`card ${!plan?'disabled-card':''}`}><div className="execute-card"><div><SectionTitle n="04" title="填写、回读与提交前检查" sub="执行后重新读取网页值，并检查附件、必填项和页面错误"/>{execution&&<p className="execution-result"><Check size={15}/>{execution.verified} 项回读验证 · {execution.skipped} 项跳过 · {execution.failed} 项失败</p>}</div><div className="execute-actions">{check&&<button className="secondary" disabled={!!busy} onClick={recheck}><RefreshCw size={15}/>重新检查</button>}<button className="primary" disabled={!plan||(!readyCount&&!selectedResume)||!!busy} onClick={execute}>{busy==='filling'?<LoaderCircle className="spin" size={17}/>:<Play size={17}/>}填写并验证 {readyCount} 个字段</button></div></div>{check&&<div className={`preflight ${check.ready?'ready':'pending'}`}><div><ShieldCheck size={21}/><span><strong>{check.ready?'表单已具备提交条件':'还不能提交'}</strong><small>已填写 {check.filled_count} 项 · 必填项 {check.required_total} 个 · 附件 {check.file_uploads.length} 个</small></span></div>{check.file_uploads.length>0&&<p>已上传：{check.file_uploads.join('、')}</p>}{check.required_missing.length>0&&<div><strong>仍缺少</strong><ul>{check.required_missing.map((item,i)=><li key={`${item.selector}-${i}`}>{item.label||item.field_type}</li>)}</ul></div>}{check.validation_errors.length>0&&<div><strong>页面校验提示</strong><ul>{check.validation_errors.map((item,i)=><li key={i}>{item}</li>)}</ul></div>}{check.human_challenges.length>0&&<div><strong>需要你手动完成</strong><ul>{check.human_challenges.map((item,i)=><li key={i}>{item}</li>)}</ul></div>}<footer><AlertTriangle size={14}/>当前阶段不会点击“{check.submit_labels[0]||'提交申请'}”。</footer></div>}</section>
  </div>
}

function SectionTitle({n,title,sub}:{n:string;title:string;sub:string}){return <div className="section-title"><span>{n}</span><div><h2>{title}</h2><p>{sub}</p></div></div>}
function Input({label,value,set,type='text'}:{label:string;value:string|number|null;set:(v:string)=>void;type?:string}){return <label className="field"><span>{label}</span><input type={type} value={value??''} onChange={e=>set(e.target.value)}/></label>}
function Select({label,value,values,set}:{label:string;value:string;values:string[];set:(v:string)=>void}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></label>}
function Text({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="field text"><span>{label}</span><textarea value={value} onChange={e=>set(e.target.value)}/></label>}
function EditableList<T>({title,n,items,empty,set,render}:{title:string;n:string;items:T[];empty:T;set:(v:T[])=>void;render:(x:T,i:number,edit:(i:number,p:Partial<T>)=>void)=>React.ReactNode}){const edit=(i:number,p:Partial<T>)=>{const next=[...items];next[i]={...next[i],...p};set(next)};return <section className="card"><SectionTitle n={n} title={title} sub={`共 ${items.length} 条，可手动补充和修正`}/>{items.map((x,i)=><div className="list-item" key={i}><div className="list-head"><strong>{title} {i+1}</strong><button onClick={()=>set(items.filter((_,j)=>i!==j))}>移除</button></div>{render(x,i,edit)}</div>)}<button className="add" onClick={()=>set([...items,{...empty}])}><Plus size={16}/>添加一条</button></section>}
const split=(v:string)=>v.split(/[,，、]/).map(x=>x.trim()).filter(Boolean);const message=(e:unknown)=>e instanceof Error?e.message:'操作失败';const display=(v:unknown)=>typeof v==='string'?v:JSON.stringify(v);const formatBytes=(n:number)=>n?`${(n/1024).toFixed(n>1024*1024?0:1)} ${n>1024*1024?'MB':'KB'}`:'—'
