import assert from 'node:assert/strict'
import {validateChatImage,inspectTaskUrl,targetFromDraft,formStageReady,shouldKeepChatMounted,CHAT_IMAGE_LIMIT} from './chatTask.ts'

assert.equal(validateChatImage({type:'image/png',size:900}), '')
assert.equal(validateChatImage({type:'image/webp',size:CHAT_IMAGE_LIMIT}), '')
assert.ok(validateChatImage({type:'image/gif',size:900}))
assert.ok(validateChatImage({type:'image/svg+xml',size:900}))
assert.ok(validateChatImage({type:'image/jpeg',size:CHAT_IMAGE_LIMIT+1}))
assert.ok(validateChatImage({type:'image/png',size:0}))
assert.equal(inspectTaskUrl(' https://jobs.example.test/campus#position ').hostname,'jobs.example.test')
assert.ok(inspectTaskUrl('javascript:alert(1)').error)
assert.ok(inspectTaskUrl('https://user:password@jobs.example.test/').error)
assert.ok(inspectTaskUrl('http://127.0.0.1:8000').error)
assert.ok(inspectTaskUrl('http://192.168.1.4').error)
assert.ok(inspectTaskUrl('http://localhost').error)
assert.ok(inspectTaskUrl('company.example').error)
assert.ok(inspectTaskUrl('').error)
for(const value of ['http://169.254.169.254/','https://8.8.8.8/','http://2130706433/','http://0x7f000001/','http://[::1]/','https://jobs.internal/','https://jobs.lan/','https://jobs.example.test:8443/','https://jobs.example.test/a b','https://jobs.example.test/\nabc','https://jobs.example.test\\path','https://jobs.example.test/'+ 'a'.repeat(2000),'https://%65xample.com/']) assert.ok(inspectTaskUrl(value).error,value)
assert.equal(inspectTaskUrl('https://jobs.example.test:443/').error,'')
assert.equal(inspectTaskUrl('http://jobs.example.test:80/').error,'')
const target=targetFromDraft({company:' 示例公司 ',job_title:' Agent 开发 ',city:' 北京 ',recruitment_cycle:' 2027校招 ',url:'https://jobs.example.test/campus'})
assert.equal(target.company,'示例公司')
assert.equal(target.job_title,'Agent 开发')
assert.equal(target.source_url,'https://jobs.example.test/campus')
const snapshot={fields:[{field_type:'text'}]}
assert.equal(formStageReady({stage:'homepage',form_fields:4},snapshot),false)
assert.equal(formStageReady({stage:'job_list',form_fields:4},snapshot),false)
assert.equal(formStageReady({stage:'review',form_fields:0},snapshot),false)
assert.equal(formStageReady({stage:'review',form_fields:4},{fields:[{field_type:'button'}]}),false)
assert.equal(formStageReady({stage:'application_form',form_fields:4},snapshot),true)
assert.equal(formStageReady({stage:'profile_form',form_fields:1},snapshot),true)
assert.equal(formStageReady({stage:'review',form_fields:1},snapshot),true)
assert.equal(shouldKeepChatMounted('overview',null,'account-a'),false,'Do not fetch chat history before first visit')
assert.equal(shouldKeepChatMounted('chat',null,'account-a'),true,'Mount on first explicit visit')
assert.equal(shouldKeepChatMounted('demo','account-a','account-a'),true,'Keep unsent composer when navigating away')
assert.equal(shouldKeepChatMounted('profile','account-a','account-a'),true,'Keep unsaved task card across profile navigation')
assert.equal(shouldKeepChatMounted('overview','account-a','account-b'),false,'Never keep another account chat mounted')
assert.equal(shouldKeepChatMounted('chat','account-a',null),false,'Signed-out user must not keep a chat instance')
console.log('chat task helpers: 45 synthetic assertions passed')
