import assert from 'node:assert/strict'
import {registerHooks} from 'node:module'
registerHooks({resolve(specifier,context,nextResolve){return nextResolve(specifier==='./chatTask'?'./chatTask.ts':specifier,context)}})
const {workbenchView,canContinueWorkflow,actionableNavigation}=await import('./workbenchView.ts')
const blank={hasPlan:false,hasDraftEdits:false,unresolvedQuestions:0,ready:false,hasExecution:false}
const view=(stage,extra={},options={})=>workbenchView({...blank,workflow:{stage,form_fields:0,job_id:'',navigation_candidates:[],...extra},snapshot:{fields:[]},...options})
let result=view('job_list')
assert.equal(result.showForms,false)
assert.equal(result.action,'refresh')
assert.equal(result.label,'我已在招聘网页操作，重新识别')
assert.equal(result.showNavigation,false)
result=view('unknown',{job_id:'synthetic-job-id'})
assert.equal(result.action,'refresh')
assert.match(result.title,/申请页面还没准备好/)
assert.match(result.description,/截图/)
assert.equal(result.showForms,false)
assert.equal(view('unknown',{navigation_candidates:[{id:'entry'}]}).showNavigation,false)
assert.equal(view('job_list',{navigation_candidates:[{id:'entry',kind:'open_job'}]}).action,'choose')
assert.equal(view('homepage',{navigation_candidates:[{id:'entry',kind:'browse_jobs'}]}).action,'choose')
assert.equal(view('job_detail').action,'enter')
for(const stage of ['registration_required','auth_required','verification_required']){
  result=view(stage)
  assert.equal(result.showAccountTools,true)
  assert.equal(result.showForms,false)
  assert.equal(result.action,'refresh')
}
result=view('review',{}, {ready:true})
assert.equal(result.showForms,false)
assert.notEqual(result.action,'review','Zero-field review must not imply final readiness')
const actualForm={snapshot:{fields:[{field_type:'text'}]}}
result=view('application_form',{form_fields:1},actualForm)
assert.equal(result.showForms,true)
assert.equal(result.action,'fill')
assert.equal(view('application_form',{form_fields:1},{...actualForm,hasExecution:true,unresolvedQuestions:2}).action,'questions')
assert.equal(view('review',{form_fields:1},{...actualForm,ready:true}).action,'review')
assert.equal(view('application_form',{form_fields:1,safe_next_present:true},{...actualForm,ready:true}).action,'continue')
assert.equal(view('application_form',{form_fields:1,safe_next_present:true},{...actualForm,ready:true,hasDraftEdits:true}).action,'questions','Do not navigate away from unsent edits')
assert.equal(view('homepage',{form_fields:1},actualForm).showForms,false,'Homepage search is not an application form')
const search={id:'search',kind:'search_jobs'},job={id:'job',kind:'open_job'},browse={id:'browse',kind:'browse_jobs'}
result=view('job_list',{navigation_candidates:[search],target:{job_title:' '}})
assert.equal(result.showNavigation,false)
assert.equal(result.action,'refresh')
assert.match(result.description,/搜索框/)
assert.deepEqual(result.navigationCandidates,[])
assert.deepEqual(actionableNavigation({navigation_candidates:[search,job,browse],target:{job_title:''}}).map(item=>item.id),['job','browse'])
assert.deepEqual(actionableNavigation({navigation_candidates:[search],target:{job_title:'Agent 开发'}}).map(item=>item.id),['search'])
assert.equal(view('job_list',{navigation_candidates:[search],target:{job_title:'Agent 开发'}}).showNavigation,true)
assert.equal(view('review',{form_fields:1,safe_next_present:true},{...actualForm,ready:true}).action,'review')
assert.equal(view('application_form',{form_fields:1,safe_next_present:true,requires_consent:true},{...actualForm,ready:true}).action,'refresh')
assert.equal(canContinueWorkflow({stage:'review',safe_next_present:true,requires_consent:false}),false)
assert.equal(canContinueWorkflow({stage:'profile_form',safe_next_present:true,requires_consent:true}),false)
assert.equal(canContinueWorkflow({stage:'profile_form',safe_next_present:true,requires_consent:false}),true)
result=view('unknown',{job_id:'synthetic-job-id',form_fields:29})
assert.equal(result.showForms,false)
assert.equal(result.action,'refresh')
assert.equal(result.label,'同步当前页面')
assert.match(result.title,/29 个控件/)
assert.match(result.description,/不必重复登录/)
assert.doesNotMatch(result.title,/还没准备好|未加载/)
result=view('unknown',{job_id:'observed-id',job_title:'真实岗位',message:'正文已读取，申请入口缺失'})
assert.equal(result.title,'岗位已识别，申请入口仍需核对')
assert.equal(result.description,'正文已读取，申请入口缺失')
assert.equal(result.showForms,false)
console.log('workbench view: synthetic stage and identified-job assertions passed')
